version: '3.8'

services:
  node-app:
    container_name: node-app
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/mydatabase
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=VRuAd2Nvmp4ELHh5 
      - MONGO_INITDB_DATABASE=test
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=VRuAd2Nvmp4ELHh5 
      - MONGO_INITDB_DATABASE=test
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge