version: '3.8'

services:
  node-app:
    container_name: node-app
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/ktpm
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=VRuAd2Nvmp4ELHh5
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=VRuAd2Nvmp4ELHh5
      - MONGO_INITDB_DATABASE=ktpm
    ports:
      - '27017:27017'
    volumes:
      - ./db/:/db
    # command: mongoimport --host mongodb --authenticationDatabase admin --username admin --password VRuAd2Nvmp4ELHh5 --db ktpm --collection Users --file ./db/user.json --jsonArray
    # command: bash -c 'for file in /db/*.json; do mongoimport --host mongodb --db ktpm --collection your_collection_name --file "$file" --jsonArray; done'
    networks:
      - node-network

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
